name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: zig version

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2

      - name: Install bats-core
        run: brew install bats-core

      - name: Test plugin
        run: |
          asdf plugin-add zig $GITHUB_WORKSPACE
          make test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: brew install shellcheck

      - name: Run ShellCheck
        run: make lint

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: make fmt-check
